In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-1.40892271  1.52451525 -0.30358666  1.63268934  1.13419168]


In [3]:
# Rank 1 array : Neither a row vector or a column vector
print(a.shape)

(5,)


In [4]:
print(a.T)

[-1.40892271  1.52451525 -0.30358666  1.63268934  1.13419168]


In [5]:
print(np.dot(a, a.T))

8.35344007722856


In [6]:
a = np.random.randn(5,1)

In [7]:
print(a)

[[-0.73211465]
 [ 0.32950495]
 [-1.24860564]
 [-0.06753108]
 [-0.60547137]]


In [8]:
print(a.T)

[[-0.73211465  0.32950495 -1.24860564 -0.06753108 -0.60547137]]


In [9]:
# outer product
print(np.dot(a, a.T))

[[ 0.53599186 -0.2412354   0.91412248  0.04944049  0.44327446]
 [-0.2412354   0.10857351 -0.41142174 -0.02225182 -0.19950581]
 [ 0.91412248 -0.41142174  1.55901605  0.08431969  0.75599496]
 [ 0.04944049 -0.02225182  0.08431969  0.00456045  0.04088813]
 [ 0.44327446 -0.19950581  0.75599496  0.04088813  0.36659557]]


In [10]:
b = np.random.rand(2,3,4)
print(b)

[[[0.48419104 0.28690236 0.69684334 0.32706605]
  [0.71676353 0.07263541 0.78836733 0.44294709]
  [0.19867938 0.00514301 0.25889219 0.48731449]]

 [[0.66754605 0.22501569 0.35016603 0.02570861]
  [0.05597642 0.86654774 0.08765315 0.99891757]
  [0.61386122 0.34226442 0.57409908 0.74823701]]]


In [11]:
b.reshape(3,2,4)

array([[[0.48419104, 0.28690236, 0.69684334, 0.32706605],
        [0.71676353, 0.07263541, 0.78836733, 0.44294709]],

       [[0.19867938, 0.00514301, 0.25889219, 0.48731449],
        [0.66754605, 0.22501569, 0.35016603, 0.02570861]],

       [[0.05597642, 0.86654774, 0.08765315, 0.99891757],
        [0.61386122, 0.34226442, 0.57409908, 0.74823701]]])